### ISSUE TITLE
Add C++11 Compatibility

### ISSUE THREAD

**Issue by david4096** [FDA/fda-hive#2]
As mentioned by @tetromino 

> HIVE was developed using g++ 4.x to ensure ability to build and run on CentOS 6/7 hosts with minimal modification. Unfortunately, as a result, we allowed numerous incompatibilities with the c++11 language standard to slip into the codebase, so compilation with g++ 6 fails. We are working on fixing this as soon as possible.

**Comment by tetromino** [comment]
As of commit 666e949783dc74856bcb3c9b1222afeab95ec445, we can build with g++ 6.

Fixing warning spam still remains to be done.
